import { Client } from '@/types/client.types';
import { Audit } from '@/types/audit.types';
import { Project } from '@/types/project.types';

export const mockClients: Client[] = [
  {
    id: 'c1',
    name: 'Groupe Beaumont Inc.',
    industry: 'Distribution',
    employees: 85,
    securityScore: 67,
    status: 'active',
    contactName: 'Marc Beaumont',
    contactEmail: 'marc@beaumont.ca',
    lastAuditDate: '2026-01-15',
    riskLevel: 'medium',
  },
  {
    id: 'c2',
    name: 'Clinique Santé Nord',
    industry: 'Santé',
    employees: 42,
    securityScore: 54,
    status: 'active',
    contactName: 'Dr. Sophie Tremblay',
    contactEmail: 'stremblay@santenord.ca',
    lastAuditDate: '2026-02-10',
    riskLevel: 'high',
  },
  {
    id: 'c3',
    name: 'Transport Bélanger',
    industry: 'Transport',
    employees: 120,
    securityScore: 78,
    status: 'active',
    contactName: 'Jean-Pierre Bélanger',
    contactEmail: 'jp@belanger-transport.ca',
    lastAuditDate: '2026-03-01',
    riskLevel: 'low',
  },
];

export const mockAudits: Audit[] = [
  {
    id: 'a1',
    clientId: 'c1',
    clientName: 'Groupe Beaumont Inc.',
    type: 'full',
    status: 'completed',
    score: 67,
    startDate: '2026-01-10',
    completedDate: '2026-01-15',
    findings: [
      {
        id: 'f1',
        severity: 'critical',
        title: 'Mots de passe faibles détectés',
        description: '23% des comptes utilisent des mots de passe ne respectant pas la politique.',
        status: 'open',
      },
      {
        id: 'f2',
        severity: 'high',
        title: 'MFA non activé',
        description: 'L\'authentification multi-facteurs n\'est pas activée pour 60% des comptes.',
        status: 'open',
      },
      {
        id: 'f3',
        severity: 'medium',
        title: 'Mises à jour en retard',
        description: '12 postes ont des mises à jour Windows en retard de plus de 30 jours.',
        status: 'resolved',
      },
    ],
  },
  {
    id: 'a2',
    clientId: 'c2',
    clientName: 'Clinique Santé Nord',
    type: 'compliance',
    status: 'completed',
    score: 54,
    startDate: '2026-02-05',
    completedDate: '2026-02-10',
    findings: [
      {
        id: 'f4',
        severity: 'critical',
        title: 'Données patients non chiffrées',
        description: 'Les données de santé ne sont pas chiffrées au repos sur le serveur principal.',
        status: 'open',
      },
      {
        id: 'f5',
        severity: 'critical',
        title: 'Accès non restreint aux dossiers',
        description: 'Tous les employés ont accès à l\'ensemble des dossiers patients.',
        status: 'open',
      },
      {
        id: 'f6',
        severity: 'high',
        title: 'Pas de journalisation des accès',
        description: 'Aucun log d\'accès aux données sensibles n\'est configuré.',
        status: 'open',
      },
    ],
  },
  {
    id: 'a3',
    clientId: 'c3',
    clientName: 'Transport Bélanger',
    type: 'full',
    status: 'in_progress',
    score: null,
    startDate: '2026-03-01',
    completedDate: null,
    findings: [],
  },
];

export const mockProjects: Project[] = [
  {
    id: 'p1',
    clientId: 'c1',
    clientName: 'Groupe Beaumont Inc.',
    title: 'Migration serveur Windows Server 2022',
    status: 'in_progress',
    priority: 'high',
    progress: 65,
    startDate: '2026-02-01',
    dueDate: '2026-04-15',
    assignee: 'Alexandre Dupont',
  },
  {
    id: 'p2',
    clientId: 'c2',
    clientName: 'Clinique Santé Nord',
    title: 'Déploiement Microsoft 365',
    status: 'in_progress',
    priority: 'medium',
    progress: 40,
    startDate: '2026-02-15',
    dueDate: '2026-05-01',
    assignee: 'Marie-Claude Roy',
  },
  {
    id: 'p3',
    clientId: 'c3',
    clientName: 'Transport Bélanger',
    title: 'Audit cybersécurité complet',
    status: 'in_progress',
    priority: 'high',
    progress: 25,
    startDate: '2026-03-01',
    dueDate: '2026-03-31',
    assignee: 'Alexandre Dupont',
  },
  {
    id: 'p4',
    clientId: 'c1',
    clientName: 'Groupe Beaumont Inc.',
    title: 'Installation pare-feu Fortinet',
    status: 'planned',
    priority: 'urgent',
    progress: 0,
    startDate: '2026-03-15',
    dueDate: '2026-04-01',
    assignee: 'Jean-François Morin',
  },
  {
    id: 'p5',
    clientId: 'c3',
    clientName: 'Transport Bélanger',
    title: 'Onboarding nouveau client',
    status: 'completed',
    priority: 'medium',
    progress: 100,
    startDate: '2026-01-15',
    dueDate: '2026-02-28',
    assignee: 'Marie-Claude Roy',
  },
];

export const dashboardMetrics = {
  globalScore: 67,
  activeClients: 12,
  openTickets: 7,
  criticalTickets: 2,
  activeProjects: 5,
  licensesToRenew: 4,
};
